services:

  myapp:
    image: golang:1.22-alpine
    container_name: ai-tiket-bus
    volumes:
      - ./app:/go/src/app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 8787:8787
    restart: always
    # working_dir: /go/src/app
    # command: go run main.go
