services:

  myapp:
    image: golang:1.22-alpine
    container_name: myApp
    restart: always
    ports:
      - 8989:8989
    valumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    command: go run --tags=jsoniter main.go
