services:

  myapp:
    image: golang:1.24-alpine3.20
    container_name: whatsapp-bot
    volumes:
      - ./app:/go/src/app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 8787:8787
    restart: always
    depends_on:
      - mariadb
    networks:
      - network1

  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./configs/mysql/conf.d:/etc/mysql/conf.d
      - ./volumes/database:/var/lib/mysql
      - ./volumes/sql:/sql
    networks:
      - network1
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p${MARIADB_ROOT_PASSWORD}' ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  network1:
    driver: bridge
